repos:
  - repo: local
    hooks:
      - id: zuban
        name: zuban
        entry: uv run zuban check homeassistant_api
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
    rev: "v4.1.0"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.6'
    hooks:
      - id: ruff-format
      - id: ruff-check
      - id: ruff-format
