[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "HomeAssistant-API"
version = "5.0.3"
description = "Python Wrapper for Homeassistant's REST API"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.9,<4.0"
authors = [
    { name = "GrandMoff100", email = "minecraftcrusher100@gmail.com" },
]
dependencies = [
    "aiohttp>=3,<4",
    "aiohttp-client-cache>=0,<1",
    "pydantic>=2,<3",
    "requests>=2,<3",
    "requests-cache>=1,<2",
    "ruff>=0.15.7",
    "simplejson>=3,<4",
    "ty>=0.0.24",
    "websockets>=15,<16",
]

[project.urls]
Documentation = "https://homeassistantapi.readthedocs.io"
Homepage = "https://github.com/GrandMoff100/HomeAssistantAPI"
Repository = "https://github.com/GrandMoff100/HomeAssistantAPI"

[dependency-groups]
docs = [
    "sphinx-autodoc-typehints>=1.25.2",
    "sphinx-rtd-theme>=2.0.0",
    "autodoc-pydantic>=2.0.1",
]
styling = [
    "pre-commit>=2.17.0",
    "types-docutils>=0.17.5",
    "types-requests>=2.27.9",
    "types-simplejson>=3.17.3",
    "types-toml>=0.10.4",
    "mypy>=1.8.0",
    "ruff>=0.15",
]
testing = [
    "pytest-asyncio>=1",
    "pytest-cov>=7",
    "pytest>=8",
    "aiosqlite>=0.22",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
log_cli = true
# log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",
    "def __repr__\\(self\\) -> str:",
    "raise RequestTimeoutError\\(",
    "except \\(json\\.decoder\\.JSONDecodeError, simplejson.decoder\\.JSONDecodeError\\) as err:",
    "pass",
    "last_updated < \\(now := datetime\\.now\\(\\)\\) - wait",
    "pragma: no cover"
]

[tool.ruff.lint]
exclude = [
    '.git',
    '__pycache__',
    '.github',
]
ignore = ['E501']
select = [
    'E',
    'F',
    'W',
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ['F401']
"conf.py" = ['E402']

[tool.isort]
profile = "black"

[tool.mypy]
disable_error_code = [
    "no-untyped-def",
    "name-defined",
]

[tool.hatch.build.targets.wheel]
packages = ["homeassistant_api"]

[tool.hatch.build.targets.sdist]
include = ["homeassistant_api", "homeassistant_api/py.typed"]
